require 'spec.run'

describe("(quote)", function()
	it("does nothing to numbers", function()
		assert.are.equal(run "(quote 10)", 10)
		assert.are.equal(run "(quote 10.5)", 10.5)
		assert.are.equal(run "(quote -10.5)", -10.5)
	end)
	it("does nothing to strings", function()
		assert.are.equal(run '(quote "foo")', run '"foo"')
		assert.are.equal(run '(quote "yo\nyo")', run '"yo\nyo"')
	end)
	it("does nothing to keywords/symbols", function()
		pending("is this right?")
		assert.are.equal(run "(quote :foo)", run ":foo")
		assert.are.equal(run "(quote foo)", run "foo")
	end)
	it("produces eval-able output", function()
	end)
end)
